language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - pytest
  - set -e
  - python setup.py docs
  - pip install doctr
  - doctr deploy . --built-docs docs/_build/html/